### ISSUE TITLE
OpticalModel file format

### ISSUE THREAD

**Issue by ivergara** [francescorandi/optics#21]
How should the optical models be saved? There are three different straightforward options: pickle, text, json.

1.- pickle:
  - Advantage: Would allow an easy way to save and load (whole object representation into disk).
  - Disadvantage: Not human readable.
2.- text:
  - Advantage: Human readable.
  - Disadvantage: Needs an external specification to give it meaning. Having to implement our own "parser"
3.- json:
  - Advantage: Meaning of content in file. Parser part of standard library.
  - Disadvantage: Looks usually messy with all the {}, hard to read by humans.

In my opinion, this file should be: easy to read, self explanatory. This basically excludes pickle and text, leaving json in a grey zone.

Looking for other options I found [TOML](https://github.com/toml-lang/toml)
4.- TOML:
  -Advantage: Like json plus being cleaner.
  - DisadvantageL Rather new. Parser not part of standard library.

Another option is [YAML](http://yaml.org/)
5.- YAML:
  - Advantage: Like TOML but more mature.
  - Disadvantage: By design more complex than TOML. Parser not part of standard library.

I'm inclined for TOML, but probably jsoon is less of a headache to use to start with.

Some extra [info](http://www.drdobbs.com/web-development/after-xml-json-then-what/240151851) maybe worth to read.

**Comment by francescorandi** [comment]
Thanks for the reference to the blog post. 
I'm strongly in favour of json. In the future, I'd like these libraries to be able to work as services (even if just in local networks in a lab), and json is still the most widely used format in web APIs. 
The readability can be enhanced very much by "prettyprinting" the json file, with something like 
json.dumps(object, indent=4)

Since you also agree that starting with json would be the most straightforward way to start, I'd choose json.

**Comment by ivergara** [comment]
It's just that I find json so ugly! And "prettyprinting" doesn't make it much better.

 But sure, json seems like a safe bet. I don't think that many will really go into the file to change it by hand. In any case, I don't think it'll be too difficult to change from one to another if the need arises. Worse case scenario, we could even expose a local file in TOML but a network object in json.
