### ISSUE TITLE
Oscillators parameters

### ISSUE THREAD

**Issue by ivergara** [francescorandi/optics#35]
Oscillators should have an attribute defining the number, name and eventually (optionally) min/max value for the parameters.

**Comment by francescorandi** [comment]
The parameters are now properties of the oscillator's class, which means that the min/max values and the relative control can be implemented in the setter for the properties.
I have also added an _nparams attribute. This is especially needed because for the fitting procedure all the parameters of the oscillators in a model have to be merged in a single array and then, during the minimization, to be fed back to the model, which has to reinsert them in the correct places.

**Comment by ivergara** [comment]
Closing this issue then
