### ISSUE TITLE
SpectralWeight as property

### ISSUE THREAD

**Issue by ivergara** [francescorandi/optics#49]
I like what you did there! But I have a doubt/issue/problem. The will be some lineshapes that don't have a closed analytical expression for the spectral weight, this means it'll have to be numerically computed. So far so good, now is when it can get tricky... for such a computation the limits have to be chosen and a stepsize (basically setting up the integrator). This means we have to chose a priori such values to keep the spectral weight simple enough. 

Maybe all the lineshapes integrate easily without convergence issues and so on and I'm being paranoid too early.

Another slight issue is when someone would like a partial spectral weight, although I see this happening more when dealing with the whole model than with an oscillator.

**Comment by francescorandi** [comment]
I guess that for each oscillator sigma_1 can be integrated without too many problems. Maybe we could define for each kind of oscillator some kind of effective width over which to integrate, as a function of the oscillator's parameters.

Maybe the partial spectral weight can be accessed on the model level, where it is more natural that the "basic" way to get a spectral weight is to ask for it on an interval. On the oscillator level it seems to me that, instead, the "natural" thing is to ask for the total spectral weight, since it is some kind of intrinsic physical property.

**Comment by ivergara** [comment]
We agree, total spectral weight accessed through oscillators and partial spectral weight through model. Will start working on this.

**Comment by ivergara** [comment]
Mostly implemented, with a few issues.
